# Generated by Django 5.2.1 on 2025-05-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cemail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
